version: '2'

services:
    php:
        build: ./php
        volumes:
            - ./ee:/var/www/html
        expose:
            - "9000"
        links:
            - mysql
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./ee:/var/www/html
        ports:
            - "3333:3333"
        links:
            - php
    mysql:
        image: mysql:5.7
        volumes:
            - ./.data/mysql:/var/lib/mysql
            - ./.logs/mysql:/var/log/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ee
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
